collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4659498
  brandStrength: 0.3673835
  lightness: 0.3584229
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  rhythmicContrast: 0.2885305
typography_spectrum: 0.6469534
layout_spectrum: 1
name: Joe Antonios Carpentry
