layout_spectrum: 1
typography_spectrum: 0.6469534
color:
  saturation: 1
  lightness: 0.5573477
  brandStrength: 0.7903226
  rhythmicContrast: 0.5483871
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: Joe Antonios Carpentry
